AWSTemplateFormatVersion: '2010-09-09'
Description: K8s resource for eks
Parameters:
  K8sClusterName:
    Type: String
    Default: EKS
    Description: The desired name of your AWS EKS Cluster.
  EKSVersion:
    Type: String
    Default: '1.28'
    AllowedValues:
      - 1.26
      - 1.27
      - 1.28
    Description: The desired version of your AWS EKS Cluster.
  K8sIAMRoleArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /k8s/security/iam/arn
  K8sSecurityGroupId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /k8s/security/sg/id
  K8sPublicSubnet01Id:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /k8s/network/subnet-01/id
  K8sPublicSubnet02Id:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /k8s/network/subnet-02/id
Resources:
  K8SCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref K8sClusterName
      Version: !Ref EKSVersion
      RoleArn: !Ref K8sIAMRoleArn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref K8sSecurityGroupId
        SubnetIds:
          - !Ref K8sPublicSubnet01Id
          - !Ref K8sPublicSubnet02Id
